- hosts: localhost
  gather_facts: false
  vars:
    cert_manager_namespace: coopink
    kubeconfig_path: 
    cert_manager_values: config/values.yaml
  tasks:


########## Create namespace ########## 


  - name: Create {{ cert_manager_namespace }} namespace
    k8s:
     kubeconfig: "{{ kubeconfig_path }}"
     name: "{{ cert_manager_namespace }}"
     api_version: v1
     kind: Namespace
     state: present
 


########## Add helm repository ########## 

  
  - name: Add cert-manager Helm charts repository
    kubernetes.core.helm_repository:
      kubeconfig: "{{ kubeconfig_path }}"
      name: cert-manager
      repo_url: https://charts.jetstack.io



########## Install chart ########## 

 
  - name: Install Cert-Manager chart  
    kubernetes.core.helm:
      kubeconfig: "{{ kubeconfig_path }}"
      name: cert-manager
      namespace: "{{ cert_manager_namespace }}"
      chart_ref: cert-manager/cert-manager
      chart_version: "v1.15.0" # Specify the desired version here
      values: "{{ lookup('file', '{{ cert_manager_values }}') | from_yaml }}"

########## Install webhook ########## 
## clone https://github.com/baarde/cert-manager-webhook-ovh.git before
  - name: Install Cert-Manager Webhook OVH chart
    kubernetes.core.helm:
      kubeconfig: "{{ kubeconfig_path }}"
      name: cert-manager-webhook-ovh
      namespace: "{{ cert_manager_namespace }}"
      chart_ref: ./cert-manager-webhook-ovh/deploy/cert-manager-webhook-ovh
      values:
        groupName: cert-manager-webhook-ovh




  - name: Create ovh-credentials secret
    kubernetes.core.k8s:
      kubeconfig: "{{ kubeconfig_path }}"
      state: present
      definition: 
        apiVersion: v1
        kind: Secret
        type: Opaque             
        metadata:
          name: "ovh-credentials"
          namespace: "{{ cert_manager_namespace }}"     
        data:
          applicationSecret:


          

 