apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: etherpad-ingress
  namespace: etherpad
spec:
  rules:
  - host: etherpad.z0057393.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: etherpad
            port:
              number: 9001
