apiVersion: apps/v1
kind: Deployment
metadata:
  name: etherpad
  namespace: etherpad
spec:
  replicas: 1
  selector:
    matchLabels:
      app: etherpad
  template:
    metadata:
      labels:
        app: etherpad
    spec:
      containers:
        - name: etherpad
          image: etherpad/etherpad:2.1
          ports:
            - containerPort: 9001
              protocol: TCP
          env:
            - name: DB_TYPE
              value: "postgres"
            - name: DB_HOST
              value: "etherpad-postgres"
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: "etherpad"
            - name: DB_PASS
              value: "pwd"
            - name: DB_NAME
              value: "etherpad"
            - name: ADMIN_PASSWORD
              value: "pwd"
            - name: USER_PASSWORD
              value: "pwd"
