apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: etherpad-postgres-pv-claim
  namespace: etherpad
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi

---



apiVersion: v1
kind: Service
metadata:
  name: etherpad-postgres
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: etherpad-postgres
  namespace: etherpad
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:13
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "etherpad"
            - name: POSTGRES_PASSWORD
              value: "pwd"
            - name: POSTGRES_DB
              value: "etherpad"
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
              subPath: pgdata
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: etherpad-postgres-pv-claim
