apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:alpine3.18
          env:
            - name: POSTGRES_DB
              value: coopink
            - name: POSTGRES_USER
              value: coopink
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgsql-secret
                  key: password
          ports:
            - containerPort: 5432