apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
  namespace: coopink
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
        - name: pgadmin
          image: dpage/pgadmin4
          env:
            - name: PGADMIN_DEFAULT_EMAIL
              value: "admin@example.com"
            - name: PGADMIN_DEFAULT_PASSWORD
              value: "SuperSecret"
            - name: SCRIPT_NAME
              value: "/pgadmin4"
          ports:
            - containerPort: 80
