apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: coopink
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: 
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - dns01:
        webhook:
          groupName: 'cert-manager-webhook-ovh'
          solverName: ovh
          config:
            endpoint: 
            applicationKey: 
            applicationSecretRef:
              key: applicationSecret
              name: ovh-credentials
            consumerKey: 
