apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: z0057393-prod
  namespace : coopink
spec:
  secretName: letsencrypt-prod-pub
  issuerRef:
    name: letsencrypt-prod  # Le nom de votre ClusterIssuer
    kind: ClusterIssuer
  commonName: z0057393.com  # Remplacez par votre domaine
  dnsNames:
    - z0057393.com          # Remplacez par votre domaine