apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wepolled-prod
spec:
  secretName: letsencrypt-prod
  issuerRef:
    name: letsencrypt-prod  # Le nom de votre ClusterIssuer
    kind: ClusterIssuer
  commonName: {your-domain-name}          # Remplacez par votre domaine
  dnsNames:
    - {your-domain-name}          # Remplacez par votre domaine