apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wepolled-staging
spec:
  secretName: letsencrypt-staging
  issuerRef:
    name: letsencrypt-staging  # Le nom de votre ClusterIssuer
    kind: ClusterIssuer
  commonName: {your-domain-name}          # Remplacez par votre domaine
  dnsNames:
    - {your-domain-name}          # Remplacez par votre domaine